### ISSUE TITLE
Fix item and player inspection rarely not working

### ISSUE THREAD

**Issue by incinirate** [Lemmmy/CCJam-2016#18]
Instead of having to drop something in your full inventory, pick it up, then realize its crap, so drop it, and pickup your old item.

**Comment by Lemmmy** [comment]
this is actually implemented, but for some reason it doesn't work properly with some items. it seems to occur very rarely

**Comment by CrazedProgrammer** [comment]
Never encountered this issue in my couple hours of play time, I'll reopen this issue if anything like this occurs again.
