### ISSUE TITLE
Have proper error handling

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/CCJam-2016#36]
[client/jamrogue.lua#L73](https://github.com/Lemmmy/CCJam-2016/blob/master/client/jamrogue.lua#L73)

**Comment by CrazedProgrammer** [comment]
??
It just prints the error message when it crashes lol

**Comment by incinirate** [comment]
@CrazedProgrammer True, but it would be better to have proper error handling and not print anything when actually closing the app

**Comment by CrazedProgrammer** [comment]
I agree

**Comment by CrazedProgrammer** [comment]
Improved the crash error message in https://github.com/Lemmmy/jamROGUE/commit/ccd92f2d48f133390f300e289e16a7d178b08efa .  
Real errors should not be treated silently because it decreases the mental priority of fixing the real issue.
