### ISSUE TITLE
Drop whole stack button

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/CCJam-2016#40]
For lazy people

**Comment by CrazedProgrammer** [comment]
:+1:

**Comment by CrazedProgrammer** [comment]
There's not much point in dropping only one item (from a stack of items), so I made the `Drop` button drop all items in the stack in https://github.com/Lemmmy/jamROGUE/commit/d3851b4b7772d2e2c37e8eaa914376f1dab881ae
