### ISSUE TITLE
"You ate a health vial"

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/CCJam-2016#41]
probably potion too

**Comment by dmarcuse** [comment]
And water bottle

**Comment by Lemmmy** [comment]
The water bottle one only happens sometimes but not all the time, and i know why too

**Comment by Lemmmy** [comment]
Related to #37

**Comment by dmarcuse** [comment]
Oh that's strange I've only ever seen it as `you ate a water bottle`

**Comment by CrazedProgrammer** [comment]
Fixed in https://github.com/Lemmmy/jamROGUE/commit/fd27463efc153f6e5197348fb58c3b8d34170907
