### ISSUE TITLE
Locked chest sacrificing

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/CCJam-2016#5]
You should be able to sacrifice a weapon to bash open locked chests with a chance of it breaking the loot inside

**Comment by incinirate** [comment]
Loot\* soz for me bad spelling

**Comment by Lemmmy** [comment]
thanks

**Comment by CrazedProgrammer** [comment]
Added in https://github.com/Lemmmy/jamROGUE/commit/ffec57fa053a85fc4398223f7bc469a8f57689d8 and https://github.com/Lemmmy/jamROGUE/commit/167ab9bf3907c0cb68f91c1f535c318eb7969cc9
