### ISSUE TITLE
Installer puts 'jamrogue' in '/' instead of replacing installer

### ISSUE THREAD

**Issue by LDDestroier** [Lemmmy/CCJam-2016#50]
If there isn't a reason why the installer shouldn't always place the jamrogue program at root, please change that. It'd make installing jamrogue on SimSoft easier.

**Comment by incinirate** [comment]
Mainly it's just that all the IOs would have to be replaced with resolves. Not that big of a deal, I might do it today if I have time.

**Comment by Lemmmy** [comment]
> Mainly it's just that all the IOs would have to be replaced with resolves. Not that big of a deal, I might do it today if I have time.

no, ape and i have plans to change the entire IO system so don't bother

> If there isn't a reason why the installer shouldn't always place the jamrogue program at root

some people want to install jamrogue in a subdirectory. i will make it a setting

note that no commits are going to be made and no pull requests are going to be accepted until after ccjam
